blog/urls.py
from django.urls import path
from blog.feeds import LatestEntriesFeed
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('' , blog_view, name="blog_home"), 
    path('<int:pid>/' , blog_detail_view, name="blog_detail"),
    path('category/<str:cat_name>/', blog_view, name="blog_category"),
    path('tag/<str:tag_name>/', blog_view, name="blog_tag"),
    path('author/<str:author_username>/', blog_view, name="blog_author"),
    path('search/', blog_search_view, name='blog_search'),
    path("rss/feed/", LatestEntriesFeed()),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from core.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from debug_toolbar.toolbar import debug_toolbar_urls

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    re_path(r'^robots\.txt', include('robots.urls')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += debug_toolbar_urls()

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [
    path('' ,index_view,name='index'), 
    path('about',about_view,name='about'),
    path('contact',contact_view,name='contact'),
    path('newsletter',newsletter_view,name='newsletter')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import Truncator
from django.utils.html import strip_tags
from taggit.managers import TaggableManager


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ManyToManyField(Category)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    counted_view = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    is_login_required = models.BooleanField(default=False)
    date_time_created = models.DateTimeField(auto_now_add=True)
    date_time_modified = models.DateTimeField(auto_now=True)
    date_time_published = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-date_time_created',]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:blog_detail", kwargs={"pid": self.id})
    

        # def snippets(self):
    #     return self.content[:100] + "..."

    def excerpt(self, word_count=30):
        cleaned_text = strip_tags(self.content)
        return Truncator(cleaned_text).words(word_count, truncate=' ...')


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    is_approved = models.BooleanField(default=False)
    date_time_created = models.DateTimeField(auto_now_add=True)
    date_time_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-date_time_created',]

blog/forms.py
from django import forms
from captcha.fields import CaptchaField
from blog.models import *


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['post', 'name', 'email', 'subject', 'message']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from blog.models import *
from blog.forms import CommentForm
from django.contrib import messages
from django.urls import reverse
from django.http import HttpResponseRedirect


def blog_view(request, **kwargs):
    posts = Post.objects.filter(
        date_time_published__lte=timezone.now(), status=True)
    if kwargs.get('cat_name') != None:
        posts = posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])
    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username=kwargs['author_username'])
    posts = Paginator(posts, 3)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.page(1)
    except EmptyPage:
        posts = posts.page(1)
    context = {
        'posts': posts,
    }
    return render(request, 'blog/blog-home.html', context)


def blog_detail_view(request, pid):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                'Your message submited successfully')
        else:
            messages.add_message(request, messages.ERROR,
                            'Your message did not submit.')    
    posts = Post.objects.filter(
        date_time_published__lte=timezone.now(), status=True)
    post = get_object_or_404(
        Post, id=pid, date_time_published__lte=timezone.now(), status=True)
    if post.is_login_required and not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('accounts:login'))
    else:
        comments = Comment.objects.filter(
            post=post.id, is_approved=True).order_by('-date_time_created')
        post_list = list(posts)
        try:
            current_index = post_list.index(post)
        except ValueError:
            current_index = -1

        prev_post = post_list[current_index - 1] if current_index > 0 else None
        next_post = post_list[current_index +
                            1] if current_index < len(post_list) - 1 else None

        post.counted_view += 1
        post.save()

        form = CommentForm()

        context = {
            'post': post,
            'prev_post': prev_post,
            'next_post': next_post,
            'comments': comments,
            'form': form,
        }
        return render(request, 'blog/blog-detail.html', context)


# def blog_category_view(request, cat_name):
#     posts = Post.objects.filter(date_time_published__lte=timezone.now(), status=True).filter(category__name=cat_name)
#     context = {
#         'posts': posts,
#     }
#     return render(request, 'blog/blog-home.html', context)


def blog_search_view(request):
    posts = Post.objects.filter(
        date_time_published__lte=timezone.now(), status=True)
    if request.method == 'GET':
        if s := request.GET.get('s'):
            posts = posts.filter(content__contains=s)
    context = {
        'posts': posts,
    }
    return render(request, 'blog/blog-home.html', context)

blog/templates/blog/blog-ads.html
{% load static %}
<div class="single-sidebar-widget ads-widget">
  <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt="" /></a>
</div>

blog/templates/blog/blog-detail.html
{% extends "_base.html" %} {% load static %} {% load humanize %} {% load blog-tags %} {% block content %}
<!-- start banner Area -->
<section class="relative about-banner">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">{{post.title}}</h1>
        <p class="text-white link-nav">
          <a href="{% url "core:index" %}">Home </a> <span class="lnr lnr-arrow-right"></span><a href="{% url "blog:blog_home" %}">Blog </a> <span class="lnr lnr-arrow-right"></span> {{post.title}}
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 posts-list">
        <div class="single-post row">
          <div class="col-lg-12">
            <div class="feature-img">
              <img class="img-fluid" src="{{post.image.url}}" alt="" />
            </div>
          </div>
          <div class="col-lg-3 col-md-3 meta-details">
            <ul class="tags">
              {% for cat in post.category.all %}
              <li><a href="#">{{cat.name}}</a>{% if not forloop.last%},{% endif %}</a></li>
              {% endfor %}
            </ul>
            <div class="user-details row">
              <p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{post.author.get_full_name}}</a> <span class="lnr lnr-user"></span></p>
              <p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.date_time_published|date:"d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
              <p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_view}} Views</a> <span class="lnr lnr-eye"></span></p>
              <p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{comments|length}} Comments</a> <span class="lnr lnr-bubble"></span></p>
              <ul class="social-links col-lg-12 col-md-12 col-6">
                <li>
                  <a href="#"><i class="fa fa-facebook"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-twitter"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-github"></i></a>
                </li>
                <li>
                  <a href="#"><i class="fa fa-behance"></i></a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-9 col-md-9">
            <h3 class="mt-20 mb-20">{{post.title}}</h3>
            <p class="excert">{{post.content|safe}}</p>
          </div>
        </div>
        <div class="navigation-area">
          <div class="row">
            <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
              {% if prev_post %}
              <div class="thumb">
                <a href="{% url 'blog:blog_detail' pid=prev_post.id %}"><img class="img-fluid" style='max-width: 100px;' src="{{ prev_post.image.url }}" alt="" /></a>
              </div>
              <div class="arrow">
                <a href="{% url 'blog:blog_detail' pid=prev_post.id %}"><span class="lnr text-white lnr-arrow-left"></span></a>
              </div>
              <div class="detials">
                <p>Prev Post</p>
                <a href="{% url 'blog:blog_detail' pid=prev_post.id %}"><h4>{{ prev_post.title }}</h4></a>
              </div>
              {% endif %}
            </div>
            <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
              {% if next_post %}
              <div class="detials">
                <p>Next Post</p>
                <a href="{% url 'blog:blog_detail' pid=next_post.id %}"><h4>{{ next_post.title }}</h4></a>
              </div>
              <div class="arrow">
                <a href="{% url 'blog:blog_detail' pid=next_post.id %}"><span class="lnr text-white lnr-arrow-right"></span></a>
              </div>
              <div class="thumb">
                <a href="{% url 'blog:blog_detail' pid=next_post.id %}"><img class="img-fluid" style='max-width: 100px;' src="{{ next_post.image.url }}" alt="" /></a>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="comments-area">
          <h4>{{comments|length}} Comments</h4>
          {% for comment in comments %}
            <div class="comment-list">
              <div class="single-comment justify-content-between d-flex">
                <div class="user justify-content-between d-flex">
                  <div class="thumb">
                    <img src="{% static 'img/blog/c1.jpg' %}" alt="" />
                  </div>
                  <div class="desc">
                    <h5><a href="#">{{comment.name}}</a></h5>
                    <p class="date">{{comment.date_time_created|naturalday}}</p>
                    <p class="comment">{{comment.message}}</p>
                  </div>
                </div>
              </div>
            </div>
          {% empty %}
            <p>There is no comments here yet, be the first one to share your thought.</p>
          {% endfor %}
        </div>
        <div class="comment-form">
          <h4>Leave a Comment</h4>
          <form method='post' action="{% url 'blog:blog_detail' pid=post.id %}">
            {% csrf_token %}
            <input type="hidden" name="post" value={{post.id}}>
            {% if request.user.is_authenticated %}
              <input type="hidden" name="name" value={{request.user.first_name}}>
              <input type="hidden" name="email" value={{request.user.email}}>
						{% else %}
              <div class="form-group form-inline">
                <div class="form-group col-lg-6 col-md-12 name">
                  <input type="text" class="form-control" name="name" placeholder="Enter Name"
                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
                </div>
                <div class="form-group col-lg-6 col-md-12 email">
                  <input type="email" class="form-control" name="email" placeholder="Enter email address"
                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
                </div>
              </div>
						{% endif %}
            <div class="form-group">
              <input type="text" class="form-control" name="subject" placeholder="Subject" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'" />
            </div>
            <div class="form-group">
              <textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
            </div>
            <button type="submit" class="primary-btn text-uppercase">Post Comment</a>
          </form>
        </div>
      </div>
      <div class="col-lg-4 sidebar-widgets">
        <div class="widget-wrap">
          <div class="single-sidebar-widget search-widget">
            <form class="search-form" action="#">
              <input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" />
              <button type="submit"><i class="fa fa-search"></i></button>
            </form>
          </div>

          {% include "blog/blog-writer.html" %}
          
          {% include "blog/blog-tags.html" %}

          {% latest_post %}

          {% include "blog/blog-ads.html" %}
          <div class="single-sidebar-widget post-category-widget">
            <h4 class="category-title">Post Catgories</h4>
            <ul class="cat-list">
              <li>
                <a href="#" class="d-flex justify-content-between">
                  <p>Technology</p>
                  <p>37</p>
                </a>
              </li>
              <li>
                <a href="#" class="d-flex justify-content-between">
                  <p>Lifestyle</p>
                  <p>24</p>
                </a>
              </li>
              <li>
                <a href="#" class="d-flex justify-content-between">
                  <p>Fashion</p>
                  <p>59</p>
                </a>
              </li>
              <li>
                <a href="#" class="d-flex justify-content-between">
                  <p>Art</p>
                  <p>29</p>
                </a>
              </li>
              <li>
                <a href="#" class="d-flex justify-content-between">
                  <p>Food</p>
                  <p>15</p>
                </a>
              </li>
              <li>
                <a href="#" class="d-flex justify-content-between">
                  <p>Architecture</p>
                  <p>09</p>
                </a>
              </li>
              <li>
                <a href="#" class="d-flex justify-content-between">
                  <p>Adventure</p>
                  <p>44</p>
                </a>
              </li>
            </ul>
          </div>
          <div class="single-sidebar-widget newsletter-widget">
            <h4 class="newsletter-title">Newsletter</h4>
            <p>Here, I focus on a range of items and features that we use in life without giving them a second thought.</p>
            <div class="form-group d-flex flex-row">
              <div class="col-autos">
                <div class="input-group">
                  <div class="input-group-prepend">
                    <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i></div>
                  </div>
                  <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" />
                </div>
              </div>
              <a href="#" class="bbtns">Subcribe</a>
            </div>
            <p class="text-bottom">You can unsubscribe at any time</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End post-content Area -->
{% endblock content %}

blog/templates/blog/blog-home.html
{% extends "_base.html" %} {% load blog-tags %} {% load static %} {% block content %}
<!-- start banner Area -->
<section class="banner-area relative blog-home-banner" id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content blog-header-content col-lg-12">
        <h1 class="text-white">Dude You’re Getting a Telescope</h1>
        <p class="text-white">There is a moment in the life of any aspiring astronomer that it is time to buy that first</p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start top-category-widget Area -->
<section class="top-category-widget-area pt-90 pb-90">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <div class="single-cat-widget">
          <div class="content relative">
            <div class="overlay overlay-bg"></div>
            <a href="#" target="_blank">
              <div class="thumb">
                <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget1.jpg' %}" alt="" />
              </div>
              <div class="content-details">
                <h4 class="content-title mx-auto text-uppercase">Social life</h4>
                <span></span>
                <p>Enjoy your social life together</p>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="single-cat-widget">
          <div class="content relative">
            <div class="overlay overlay-bg"></div>
            <a href="#" target="_blank">
              <div class="thumb">
                <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget2.jpg' %}" alt="" />
              </div>
              <div class="content-details">
                <h4 class="content-title mx-auto text-uppercase">Politics</h4>
                <span></span>
                <p>Be a part of politics</p>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="single-cat-widget">
          <div class="content relative">
            <div class="overlay overlay-bg"></div>
            <a href="#" target="_blank">
              <div class="thumb">
                <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget3.jpg' %}" alt="" />
              </div>
              <div class="content-details">
                <h4 class="content-title mx-auto text-uppercase">Food</h4>
                <span></span>
                <p>Let the food be finished</p>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End top-category-widget Area -->

<!-- Start post-content Area -->
<section class="post-content-area">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 posts-list">
        {% for post in posts %}
                <div class="single-post row">
          <div class="col-lg-3 col-md-3 meta-details">
            <ul class="tags">
              {% for cat in post.category.all %}
              <li><a href="{% url 'blog:blog_category' cat_name=cat.name %}">{{cat.name}}</a>{% if not forloop.last%},{% endif %}</li>
              {% endfor %}
            </ul>
            <div class="user-details row">
              <p class="user-name col-lg-12 col-md-12 col-6"><a href="{% url "blog:blog_author" author_username=post.author.username %}">{{post.author.get_full_name}}</a> <span class="lnr lnr-user"></span></p>
              <p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.date_time_published|date:"d M Y"}}</a> <span class="lnr lnr-calendar-full"></span></p>
              <p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_view}} Views</a> <span class="lnr lnr-eye"></span></p>
              <p class="comments col-lg-12 col-md-12 col-6"><a href="#">{% comments_count post.id %} Comments</a> <span class="lnr lnr-bubble"></span></p>
            </div>
          </div>
          <div class="col-lg-9 col-md-9">
            <div class="feature-img">
              <img class="img-fluid" src="{{post.image.url}}" alt="" />
            </div>
            <a class="posts-title" href="{% url "blog:blog_detail" pid=post.id %}"><h3>{{post.title}}</h3></a>
            <p class="excert">
              {% comment %} {{post.content | truncatewords:50}} {% endcomment %}
              {{post.excerpt}}
            </p>
            <a href="{% url "blog:blog_detail" pid=post.id %}" class="primary-btn">View More</a>
          </div>
        </div>
        {% endfor %}
        <nav class="blog-pagination justify-content-center d-flex">
          <ul class="pagination">
            {% if posts.has_previous %}
              <li class="page-item">
                <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
                  <span aria-hidden="true">
                    <span class="lnr lnr-chevron-left"></span>
                  </span>
                </a>
              </li>
            {% endif %}
            {% for i in posts.paginator.page_range  %}
              {% if posts.number == i %}
                <li class="page-item active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                {% else %}
                <li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                {% endif %}
            {% endfor %}
            {% if posts.has_next %}
              <li class="page-item">
                <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
                  <span aria-hidden="true">
                    <span class="lnr lnr-chevron-right"></span>
                  </span>
                </a>
              </li>
            {% endif %}
          </ul>
        </nav>
      </div>
      <div class="col-lg-4 sidebar-widgets">
        <div class="widget-wrap">
          {% include "blog/blog-search.html" %}

          {% include "blog/blog-writer.html" %}

          {% latest_post %}
          
          {% postcategories %}
          
          {% include "blog/blog-ads.html" %}
          <div class="single-sidebar-widget newsletter-widget">
            <h4 class="newsletter-title">Newsletter</h4>
            <p>Here, I focus on a range of items and features that we use in life without giving them a second thought.</p>
            <div class="form-group d-flex flex-row">
              <div class="col-autos">
                <div class="input-group">
                  <div class="input-group-prepend">
                    <div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i></div>
                  </div>
                  <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" />
                </div>
              </div>
              <a href="#" class="bbtns">Subcribe</a>
            </div>
            <p class="text-bottom">You can unsubscribe at any time</p>
          </div>
          <div class="single-sidebar-widget tag-cloud-widget">
            <h4 class="tagcloud-title">Tag Clouds</h4>
            <ul>
              <li><a href="#">Technology</a></li>
              <li><a href="#">Fashion</a></li>
              <li><a href="#">Architecture</a></li>
              <li><a href="#">Fashion</a></li>
              <li><a href="#">Food</a></li>
              <li><a href="#">Technology</a></li>
              <li><a href="#">Lifestyle</a></li>
              <li><a href="#">Art</a></li>
              <li><a href="#">Adventure</a></li>
              <li><a href="#">Food</a></li>
              <li><a href="#">Lifestyle</a></li>
              <li><a href="#">Adventure</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End post-content Area -->
{% endblock content %}

blog/templates/blog/blog-search.html
{% load static %}
<div class="single-sidebar-widget search-widget">
  <form class='search-form' action="{% url 'blog:blog_search' %}" method='get'>
    <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'" />
    <button type="submit"><i class="fa fa-search"></i></button>
  </form>
</div>

blog/templates/blog/blog-tags.html
{% load static %}

<div class="single-sidebar-widget tag-cloud-widget">
  <h4 class="tagcloud-title">Tag Clouds</h4>
  <ul>
    {% for tag in post.tags.all  %}
        <li><a href="{% url 'blog:blog_tag' tag_name=tag.name %}">{{tag.name}}</a></li>
    {% endfor %}
  </ul>
</div>

blog/templates/blog/blog-writer.html
{% load static %}
<div class="single-sidebar-widget user-info-widget">
  <img src="{% static 'img/blog/user-info.png' %}" alt="" />
  <a href="#"><h4>{{post.author.get_full_name}}</h4></a>
  <p>Senior blog writer</p>
  <ul class="social-links">
    <li>
      <a href="#"><i class="fa fa-facebook"></i></a>
    </li>
    <li>
      <a href="#"><i class="fa fa-twitter"></i></a>
    </li>
    <li>
      <a href="#"><i class="fa fa-github"></i></a>
    </li>
    <li>
      <a href="#"><i class="fa fa-behance"></i></a>
    </li>
  </ul>
  <p>
    Boot camps have its supporters and its detractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have its supporters and its
    detractors.
  </p>
</div>

blog/templates/blog/latest-posts.html
{% load humanize %}
{% load static %}

<div class="single-sidebar-widget popular-post-widget">
  <h4 class="popular-title" style='margin-bottom:20px;'>Latest Posts</h4>
  {% for post in posts %}
  <div class="single-post-list d-flex flex-row align-items-center">
    <div class="thumb">
      <img class="img-fluid" style='max-width: 100px;' src="{{post.image.url}}" alt="" />
    </div>
    <div class="details">
      <a href="{% url "blog:blog_detail" pid=post.id %}"><h6>{{post.title|truncatewords:3}}</h6></a>
      {% comment %} <p>{{post.date_time_published|date:"d M Y"}}</p> {% endcomment %}
      <p>{{post.date_time_published|naturaltime}}</p>
    </div>
  </div>
  {% endfor %}
  <div class="popular-post-list"></div>
</div>

blog/templates/blog/posts-categories.html
{% load static %}

<div class="single-sidebar-widget post-category-widget">
  <h4 class="category-title">Post Catgories</h4>
  <ul class="cat-list">
    {% for cat, count in categories.items %}
    <li>
      <a href="{% url 'blog:blog_category' cat_name=cat %}" class="d-flex justify-content-between">
        <p>{{cat}}</p>
        <p>{{count}}</p>
      </a>
    </li>
    {% endfor %}
  </ul>
</div>